print("============")
print("Biodata Diri")
nama = input("Masukkan Nama Lengkap: ")
ttl = input("Masukkan Tempat, Tanggal, Lahir: ")
alamat = input("Masukkan Alamat: ")
no_hp = input("Masukkan No.HP: ")
prodi = input("Masukkan Program Studi: ")
hobi = input("Masukkan Hobi: ")

print("============")
print ("Nama Lengkap: "+ nama)
print ("TTL: "+ ttl)
print ("Alamat: "+ alamat)
print ("No.HP: "+ no_hp)
print ("Program Studi: "+ prodi)
print ("Hobi: "+ hobi)